### ISSUE TITLE
about interpolate range

### ISSUE THREAD

**Issue by cemysf** [cvhciKIT/sloth#127]
hello, is there any guide about using the "interpolate range" option?

it sounds useful but I couldn't find anything in the official documentation, also when I try to apply it gives this error: 

```Error: Annotation count differs in first and last labeled frames, aborting```

**Comment by nilsonholger** [comment]
Nope, sorry, but no documentation (yet). This was a quick hack, and while it's in there already, it's not yet considered mature enough. But your error seems to be very clear IHMO...you're trying to interpolate between two frames with a different number of annotations, which this feature simply can't do, as its linearly interpolating between two given annotation lists, in the order they appear in that list. You can check [annotations/model.py](https://github.com/cvhciKIT/sloth/blob/master/sloth/annotations/model.py#L980) for further information.

**Comment by nilsonholger** [comment]
So, I looked into this a bit further. It seems likely that your problem is caused by multiple issues...the short answer would be "you're using it wrong"...the elaborated answer "it's complicated"...

- unlabeled objects must have `"unlabeled": true` set (this will also cause a red marker to appear in the GUI, to mark an image as `labeled`, simply press `SPACE`)...you can add these by hand or by using `sloth appendfiles --unlabeled <labelfile> <image_file1> <image_file2> ...` when creating the label file, sadly, using the GUIs `Add Image` functionality does not consider setting this label (yet, this should be a separate bug report), also the two images your are trying to interpolate between must **not** be marked as `unlabeled`
- the interpolate function tries to ensure that your labels are as consistent between the two frames as it possibly can...each attribute **must** have a `class` as well as a `type` to distinguish between different objects of the same type, e.g. add to your config:
    ```
    LABELS = (
        {
            'attributes': {
                'type':      'rect',
                'class':     'my_class'
             },
            'inserter': 'sloth.items.RectItemInserter',
            'item':     'sloth.items.RectItem',
            'hotkey':   'b',
            'text':     'Button (near)'
        },
    ...
    ```
    so that in your label file you will get:
    ```
    ...
    annotations: [
                {
                    class: my_class,
                    type: rect,
    ...
    ```
- these labels (with `class` as well as `type`) must be in the exact same order, otherwise the function can't work

Hope this helps a bit, again, the interpolate function is not yet mature enough and we definitely need to fix a few things and especially document it, so **pull requests welcome!!!** (it was published upstream already only because we were asked by multiple sources whether such functionality exists, which it already did, so sorry for the confusion)

**Comment by cemysf** [comment]
ok, I can use it now
it looks like it is working for just one annotation in two files, but it fails with multiple annotations

I will try to fix it, thank you very much for your help
